
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.io.FileInputStream
import java.util.Properties

plugins {
	alias(libs.plugins.android.application)
	alias(libs.plugins.devtools.ksp)
	alias(libs.plugins.hilt.android)
}

apply(from = rootProject.file("app/PXTasks.gradle.kts"))

kotlin {
	compilerOptions {
		jvmTarget = JvmTarget.JVM_17
	}
}

android {
	namespace = "sh.siava.pixelxpert"
	compileSdk = 36

	defaultConfig {
		applicationId = "sh.siava.pixelxpert"
		minSdk = 36
		targetSdk = 36
		// defaultConfig.versionCode/versionName are CONFIGURATION-time scalars and are read BEFORE
		// the incrementCanaryVersion task runs, so they would always be one build behind. They are
		// therefore intentionally placeholders here -- the authoritative, post-increment values are
		// stamped onto the variant OUTPUT lazily in androidComponents { onVariants { ... } } below,
		// which AGP resolves at execution time (after the increment task has bumped version.properties).
		// See the ordering-contract comment in that block.
		versionCode = 1
		versionName = "AutoGeneratedLater"
		ndk {
			//noinspection ChromeOsAbiSupport
			abiFilters.add("arm64-v8a")
		}
	}

	val keystorePropertiesFile = rootProject.file("ReleaseKey.properties")
	var releaseSigning = signingConfigs.getByName("debug")

	try {
		val keystoreProperties = Properties()
		FileInputStream(keystorePropertiesFile).use { inputStream ->
			keystoreProperties.load(inputStream)
		}

		releaseSigning = signingConfigs.create("release") {
			keyAlias = keystoreProperties.getProperty("keyAlias")
			keyPassword = keystoreProperties.getProperty("keyPassword")
			storeFile = rootProject.file(keystoreProperties.getProperty("storeFile"))
			storePassword = keystoreProperties.getProperty("storePassword")
		}
	} catch (e: Exception) {
		// Graceful fallback: when ReleaseKey.properties is absent or unreadable
		// (e.g. CI without the signing secret), keep building with the debug key.
		// Log a warning so a genuine keystore misconfig stays diagnosable.
		logger.warn("Release keystore not loaded (${e.message}); release build will fall back to debug signing.")
	}

	buildTypes {
		release {
			isMinifyEnabled = true
			isShrinkResources = true
			proguardFiles("proguard-android-optimize.txt", "proguard.pro", "proguard-rules.pro")
			signingConfig = releaseSigning
		}
		debug {
			isDebuggable = true
			isMinifyEnabled = false
			isShrinkResources = false
			// Sign debug builds with AGP's default debug keystore, not the release key,
			// so the release signing material never touches local/dev/CI debug artifacts.
		}
	}

	buildFeatures{
		viewBinding = true
		buildConfig = true
		aidl = true
	}

	compileOptions {
		isCoreLibraryDesugaringEnabled = true

		sourceCompatibility = JavaVersion.VERSION_17
		targetCompatibility = JavaVersion.VERSION_17
	}

	packaging {
		jniLibs.excludes += setOf(
			"**/libpytorch_jni_lite.so"
		)
	}
}

androidComponents {
	onVariants { variant ->
		// ORDERING CONTRACT (fix for the "APK lags one build behind its metadata" bug):
		// "increment-then-stamp-everything". incrementCanaryVersion (ordered to run BEFORE
		// assembleRelease in app/PXTasks.gradle.kts) computes the NEXT code, persists it to
		// version.properties, and stamps module.prop + all latest*/MagiskModuleUpdate* JSON
		// descriptors. The APK's own versionCode/versionName must describe that SAME next version.
		//
		// We achieve that by stamping the variant OUTPUT (not defaultConfig) via a LAZY provider:
		// getVersionInfoProvider() reads version.properties, and AGP resolves output.versionCode/
		// versionName at task-execution time -- i.e. AFTER incrementCanaryVersion has written the
		// bumped value. The result: the embedded APK versionCode/versionName, the module.prop inside
		// the zip, and the latest*.json OTA descriptors all describe one identical version.
		val versionInfoProvider = getVersionInfoProvider()
		variant.outputs.forEach { output ->
			output.versionCode.set(versionInfoProvider.map { it.code })
			output.versionName.set(versionInfoProvider.map { it.name })
		}
	}
}

dependencies {
	implementation(project(":annotations"))
	annotationProcessor(project(":annotationProcessor"))
	coreLibraryDesugaring(libs.desugar.jdk.libs)

	compileOnly(files("lib/api-82.jar"))
	compileOnly(files("lib/api-82-sources.jar"))

	implementation(project(":Submodules:RangeSliderPreference"))

	implementation (libs.androidx.constraintlayout)
	implementation (libs.androidx.navigation.fragment.ktx)
	implementation (libs.androidx.navigation.ui.ktx)
	implementation (libs.androidx.fragment.ktx)
	implementation (libs.androidx.appcompat)
	implementation (libs.androidx.annotation)
	implementation (libs.androidx.preference.ktx)
	implementation (libs.androidx.recyclerview)
	implementation (libs.android.material)
	implementation (libs.androidx.ui.geometry)
	//noinspection KtxExtensionAvailable
	implementation (libs.androidx.activity)
	implementation (libs.androidx.work.runtime)
	implementation (libs.androidx.concurrent.futures)
	implementation (libs.androidx.transition)

	// The core module that provides APIs to a shell
	implementation (libs.libsuCore)
	// Optional: APIs for creating root services. Depends on ":core"
	implementation (libs.libsuService)
	// Optional: Provides remote file system support
	implementation (libs.libsuNIO)

	implementation (libs.remotepreferences)
	// Remote Preferences for Xposed Module prefs
	implementation (libs.colorpicker) //Color Picker Component for UI
	implementation (libs.persian.date.time) //Persian Calendar

//	implementation (libs.markdown) //Markdown reader

	// Search Preference
	implementation (libs.androidx.cardview)
	implementation (libs.apache.commons.text)

	implementation (libs.androidx.swiperefreshlayout)

	// Class initializer
	// https://mvnrepository.com/artifact/org.objenesis/objenesis
	implementation (libs.objenesis)

	implementation (libs.ntpClient) //NTP Client

	//Google Subject Segmentation - MLKit
	implementation (libs.play.services.mlkit.subject.segmentation)
	implementation (libs.play.services.base)

	// Splash screen
	implementation (libs.androidx.core.splashscreen)

	// Lottie
	implementation(libs.lottie)

	implementation (libs.prdownloader)

	implementation (libs.pytorch.android.lite)
	implementation (libs.pytorch.android.torchvision.lite)
	implementation (libs.gson)

	implementation(libs.androidx.ui)
	implementation(libs.androidx.localbroadcastmanager)

	implementation(libs.hilt.android)
	ksp(libs.hilt.android.compiler)

	compileOnly(libs.lsposed.api)
	implementation(libs.lsposed.service)

	//mark-down view for changelog
	implementation(libs.markdownview.android)
}
